version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://muzammil:khan@cluster0.nwe9ct0.mongodb.net/authservice
      - JWT_SECRET=muzammil
      - PORT=5000
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://muzammil:khan@cluster0.nwe9ct0.mongodb.net/notificationservice
      - RABBITMQ_URI=amqp://rabbitmq
      - PORT=5001
    depends_on:
      - mongo
      - rabbitmq

  real-time-service:
    build: ./real-time-service
    ports:
      - "5002:5002"
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - PORT=5002
    depends_on:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "start"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
