openapi: 3.0.0
info:
  title: Notification Service API
  version: 1.0.0
  description: API endpoints for managing notifications
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the notification.
        userId:
          type: string
          description: ID of the user to whom the notification belongs.
        message:
          type: string
          description: Notification message.
        read:
          type: boolean
          description: Indicates if the notification has been read.
      required:
        - userId
        - message

paths:
  /api/notifications:
    post:
      summary: Create a new notification
      tags: [Notifications]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
    get:
      summary: Get all notifications
      tags: [Notifications]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
  /api/notifications/{id}:
    get:
      summary: Get a specific notification by ID
      tags: [Notifications]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Notification ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
    put:
      summary: Mark a notification as read
      tags: [Notifications]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Notification ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized
